# Generated by Django 5.0.7 on 2024-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DABubble', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
