# Generated by Django 5.0.7 on 2024-08-28 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0006_channelmodel_messagemodel_threadchannelmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='createdFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='thread_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='DABubble.threadchannelmodel'),
        ),
        migrations.AlterField(
            model_name='threadchannelmodel',
            name='createdFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threadchannelmodel',
            name='threadMember',
            field=models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threadmessagemodel',
            name='thread_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='DABubble.threadchannelmodel'),
        ),
    ]
