# Generated by Django 5.0.7 on 2024-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0007_rename_channelmember_channelmodel_channelmembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='createdFrom',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
