# Generated by Django 5.0.7 on 2024-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0009_alter_messagemodel_channel_alter_messagemodel_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechannelmodel',
            name='createdFrom',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
