# Generated by Django 5.0.7 on 2024-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0010_privatechannelmodel_createdfrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechannelmodel',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='privatechannelmodel',
            name='channelDescription',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatechannelmodel',
            name='channelName',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
