# Generated by Django 5.0.7 on 2024-09-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0010_rename_thread_channel_threadmessagemodel_thread_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadchannelmodel',
            name='mainChannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_channels_id', to='DABubble.channelmodel'),
        ),
    ]
