# Generated by Django 5.0.7 on 2024-09-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0011_alter_threadchannelmodel_mainchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadchannelmodel',
            name='mainChannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_channels', to='DABubble.channelmodel'),
        ),
    ]
