# Generated by Django 5.0.7 on 2024-09-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0012_alter_threadchannelmodel_mainchannel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmessagemodel',
            old_name='thread_channel_id',
            new_name='thread_channel',
        ),
    ]
