# Generated by Django 5.0.7 on 2024-08-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0014_alter_privatechannelmodel_channelpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='privateChannel',
            field=models.BooleanField(default=False),
        ),
    ]
