# Generated by Django 5.0.7 on 2024-08-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0015_channelmodel_privatechannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessagemodel',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='privatemessagemodel',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PrivateChannelModel',
        ),
        migrations.DeleteModel(
            name='PrivateMessageModel',
        ),
    ]
