# Generated by Django 5.0.7 on 2024-09-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0016_alter_messagemodel_messagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessagemodel',
            name='messageData',
            field=models.FileField(blank=True, null=True, upload_to='ulpoads/'),
        ),
    ]
